name: Build and deploy to GitHub

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+**'

env:
  BUILD_TOOLS_VERSION: 35.0.0

jobs:

  build-github:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Release APK
        id: buildRelease
        run: ./gradlew assembleDebug

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          file: ${{ env.SIGNED_RELEASE_FILE }}
          asset_name: app-release-github.apk
          tag: ${{ github.ref }}
          overwrite: true
          prerelease: ${{ env.PRE_RELEASE }}
          body: "Automatically released using GitHub actions. Release-notes will follow later."
